### ISSUE TITLE
pants - pylint isn't working yet

### ISSUE THREAD

**Issue by cognifloyd** [st2sandbox/st2#3]
Somehow, pylint needs a virtualenv with all of the dependencies installed.
It's not clear how to do that with pants.

I don't know if I have my build roots setup correctly, but I just simplified them and it didn't make a difference.

I'm also not sure about the BUILD files. It seems I need to define all the dependencies in the BUILD files, but that can't be right. I thought it inverred the deps from imports or maybe from setup.py?

**Comment by cognifloyd** [comment]
I'm much closer to getting this working (with a bunch of help from the pants community - they're very friendly and helpful).

pants now has the requirements that pylint needs, but is failing to build the pylint pex.

**Comment by cognifloyd** [comment]
Pylint runs, but it covers a lot more files than the Makefile did, so there are a lot of reported issues.

**Comment by Eric-Arellano** [comment]
Stale?

**Comment by cognifloyd** [comment]
Oh yes. pylint is working now.
