### ISSUE TITLE
Pants plugin feedback

### ISSUE THREAD

**Issue by Eric-Arellano** [st2sandbox/st2#7]
Hi! Some thoughts on your plugins at https://github.com/st2sandbox/st2/tree/pants/pants-plugins. They look great overall!

### uses_services.py

`InvalidFieldChoiceException` might be confusing wording because it's designed for `StringField`, not `StringSequenceField`. It might make more sense to use your own wording. 

Also, we would absolutely love a patch to Pants to add `valid_choices` to `StringSequenceField` if you're interested - it would mostly be copying your logic, adding a better error message, then testing in `target_test.py`.

### platform_.py

You can get more concurrency by combining those first two Gets into a MultiGet. https://www.pantsbuild.org/docs/rules-api-tips#tip-use-multiget-for-increased-concurrency

We do a horrible job documenting this right now and the system is overall a bit magical, but, if you want that @rule to show up in the dynamic UI, you need to set `level=LogLevel.DEBUG` in the `@rule` decorator. It defaults to TRACE, which as of 2.5 no longer shows up in the dynamic UI.

### exceptions.py

Missing import for type hint?

### mongo.py

todo on line 5 is stale :)

Can combine the first two `Get`s with `MultiGet`.

Probably want to pin the requirements for your `VenvPex` so it's more reproducible.

I gave you bad advice that you needed a distinct rule `mongo_is_running` and type `MongoStatus` for the sake of caching - you could inline that whole rule, Pants will still deduplicate running the script to see if Mongo is alive so that it only happens once in the whole "session". It's fine to keep a distinct rule, only not necessary.

### inspect_platform.py

Having that many fields on the dataclass makes the cache key coarser than necessary. If any of those single fields changes across runs, the cache key changes so the work can't be memoized. Granted, I doubt that `distro` is going to change from under you...probably a non-issue and premature optimization. But as a general tip, we try to keep cache keys as small as they need to be.

### target_type_rules

You're missing out on perf having a `Get` in a for loop. Probably the simplest thing to do is add a new rule that resolves a single stevedore entry point, which requires adding an input and output type like `ResolvedStevedoreEntryPoint` (without s)..then, in that current rule you have, you can do `await MultiGet(Get(ResolvedStevedoreEntryPoint, ...) for .. in request.entry_points_field.value)`. Ack that that boilerplate isn't fun :/ 

### setup_py_kwargs.py

I'm not following what this one does?

### rules.py

Are you sure about MultiGet only doing 10 at a time? That's only 10 at a time for _heterogenous_ MultiGets, like `MultiGet(Get(...), Get(...))`. The # should be unbounded for homogeneous `MultiGets` that use a generator expression.

Glad to see you went with the PytestPluginSetup approach rather than codegen. The comment about codegen is probably stale.

**Comment by cognifloyd** [comment]
> you need to set level=LogLevel.DEBUG in the @rule decorator

Good to know. Fixed

> Probably want to pin the requirements for your VenvPex so it's more reproducible.

Doesn't pants use my constraints file? At least for `mongoengine` and `pymongo`, those are present in that constraints-pants.txt.

> I doubt that distro is going to change from under you...probably a non-issue and premature optimization.

Yeah. I'll leave my Platform as is for now.

Other things:
- I resolved all the `Get`/`MultiGet` issues you mentioned. 
- I consolidated the is_mongo_running rules.

For `uses_services/target_types.py` (was `uses_services/uses_services.py`). I might look at upstreaming that later.

For `setup_py_kwargs.py`: I want to separate concerns between plugins so that a plugin could be extracted and used by others if they want. So, there's nothing st2-specific in the `stevedore_extensions` plugin. When I get around to adding python_distributions with setup_py() args, I'll do that in a different plugin. Doing this here allows me to compose the various datasources I'll end up using to construct those `setup_py()` args.

Does this comment make that clear?

https://github.com/st2sandbox/st2/blob/1e56c7983d4751f1bda42dcaa384dc1d8d873342/pants-plugins/stevedore_extensions/setup_py_kwargs.py#L38-L54

**Comment by Eric-Arellano** [comment]
> Doesn't pants use my constraints file? At least for mongoengine and pymongo, those are present in that constraints-pants.txt.

Yeah, that's true. It will unless you set `apply_requirement_constraints=False` in the `PexRequest`. 

This is actually a bit of a mess though - for tools that don't need to load your third party requirements (Black, Flake8, your plugin here), we do not want tool versions and tool constraints to be coupled with user constraints. For example, right now, if you constrain the common library `typed-ast` for your user code, that constraint needs to be compatible with Black, Isort, etc if you run those with Pants. 

The real solution we want is per-tool lockfiles, which is what that design doc you commented on is about.

> Does this comment make that clear?

Ah, okay. Yeah, that makes sense. 

Also, it's plausible that we will want to loosen the requirement that you can only have one implementation per target - we only need to decide what the merge semantics should be. (Imo, we should error upon any conflicting keys)

**Comment by cognifloyd** [comment]
> Imo, we should error upon any conflicting keys

I'd say it depends on the key. `entry_points` for example might have more than one provider. The `stevedore_extension` target is not really meant to be used for `console_scripts` for example.

**Comment by cognifloyd** [comment]
https://github.com/pantsbuild/pants/pull/15684 was merged. I think that resolves all of the feedback here.
